# permissions for end users to edit mlservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mlserver-editor-role
rules:
- apiGroups:
  - server.yakms.io
  resources:
  - mlservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - server.yakms.io
  resources:
  - mlservers/status
  verbs:
  - get
