# permissions for end users to view mlservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mlserver-viewer-role
rules:
- apiGroups:
  - server.yakms.io
  resources:
  - mlservers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - server.yakms.io
  resources:
  - mlservers/status
  verbs:
  - get
